# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testtest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testtest

  target 'testtestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
